/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;
import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.model.ElementPanier;
import fr.ufrsciencestech.panier.model.FabriqueFruit;
import fr.ufrsciencestech.panier.model.Panier;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import javax.swing.JButton;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
/**
 *
 * @author im796713
 */
public class VueGSwing extends javax.swing.JFrame implements VueG{
    
    private Panier panier=new Panier(100);
    private JFrame frame;
    
    private String platTemp="";
    private int numSelectAddFruitPlat = 0;
    private int numSelectRetraitFruitPlat = 0;
    
    private int numSelectAddFruit = 0;
    private int numSelectRetraitFruit = 0;
    private int numSelectPlat = 0;
    
    private JButton jButtonValiderBoycott = new JButton("Valider");
    private JButton jButtonValiderCreateFruit = new JButton("Valider");
    private JButton jButtonValiderCreatePlat = new JButton("Valider");
    private JButton jButtonValiderAjoutPlat = new JButton("Valider");
    
    private ArrayList<JTextField> listeParamBoycott = new ArrayList<>();
    private ArrayList<JTextField> listeParamCreateFruit = new ArrayList<>();
    private ArrayList<JTextField> listeParamCreatePlat = new ArrayList<>();
    
    private JButton jBoutonAjouterFruitPlat = new JButton("Ajouter Fruit");
    private JButton jBoutonRetirerFruitPlat = new JButton("Retirer Fruit");
    private JComboBox jComboSelectPlat = new JComboBox();
    private JComboBox jComboSelectAddPlat = new JComboBox();
    private JComboBox jComboSelectRetraitPlat = new JComboBox();
    
    private ArrayList<ElementPanier> listeAdd = new ArrayList<>();
    private ArrayList<ElementPanier> listeAddFruitPlat = new ArrayList<>();
    private ArrayList<String> listePlatPossible = new ArrayList<>();
    
    private JTextArea textAreaPlat = new JTextArea();
    
    private FabriqueFruit fabrique = new FabriqueFruit();

    public VueGSwing() {
        initComponents();
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                System.exit(0);
    }
            });
        this.pack();
        this.setVisible(true);
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelHaut = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jComboSelectAdd = new javax.swing.JComboBox<>();
        jButtonCreateFruit = new javax.swing.JButton();
        jButtonCreatePlat = new javax.swing.JButton();
        PanelMilieu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextInfos = new javax.swing.JTextArea();
        PanelBas = new javax.swing.JPanel();
        jButtonRetrait = new javax.swing.JButton();
        jComboSelectRetrait = new javax.swing.JComboBox<>();
        jButtonBoycott = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setLayout(new java.awt.BorderLayout(3, 0));

        PanelHaut.setLayout(new java.awt.GridLayout(1, 3));

        jButtonAdd.setText("+");
        jButtonAdd.setName("Plus"); // NOI18N
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        PanelHaut.add(jButtonAdd);

        jComboSelectAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection Fruit" }));
        jComboSelectAdd.setMinimumSize(new java.awt.Dimension(150, 22));
        jComboSelectAdd.setName("SelectAddFruit"); // NOI18N
        jComboSelectAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSelectAddActionPerformed(evt);
            }
        });
        PanelHaut.add(jComboSelectAdd);

        jButtonCreateFruit.setText("Créer Fruit");
        jButtonCreateFruit.setName("CreateFruit"); // NOI18N
        jButtonCreateFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateFruitActionPerformed(evt);
            }
        });
        PanelHaut.add(jButtonCreateFruit);

        jButtonCreatePlat.setText("Créer Plat");
        jButtonCreatePlat.setName("CreatePlat"); // NOI18N
        PanelHaut.add(jButtonCreatePlat);

        PanelPrincipal.add(PanelHaut, java.awt.BorderLayout.NORTH);

        PanelMilieu.setLayout(new java.awt.BorderLayout());

        jTextInfos.setColumns(20);
        jTextInfos.setRows(5);
        jTextInfos.setTabSize(1);
        jTextInfos.setText("Panier de 0 élément(s) : 0.0 euros");
        jScrollPane1.setViewportView(jTextInfos);

        PanelMilieu.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(PanelMilieu, java.awt.BorderLayout.CENTER);

        PanelBas.setLayout(new java.awt.GridLayout(1, 3));

        jButtonRetrait.setText("-");
        jButtonRetrait.setName("Minus"); // NOI18N
        jButtonRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetraitActionPerformed(evt);
            }
        });
        PanelBas.add(jButtonRetrait);

        jComboSelectRetrait.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retrait Fruit" }));
        jComboSelectRetrait.setName("SelectRetraitFruit"); // NOI18N
        PanelBas.add(jComboSelectRetrait);

        jButtonBoycott.setText("Boycott");
        jButtonBoycott.setName("Boycott"); // NOI18N
        jButtonBoycott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBoycottActionPerformed(evt);
            }
        });
        PanelBas.add(jButtonBoycott);

        PanelPrincipal.add(PanelBas, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCreateFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateFruitActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jButtonCreateFruitActionPerformed

    private void jButtonBoycottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBoycottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBoycottActionPerformed

    private void jButtonRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetraitActionPerformed

    private void jComboSelectAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSelectAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboSelectAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueGSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueGSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBas;
    private javax.swing.JPanel PanelHaut;
    private javax.swing.JPanel PanelMilieu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBoycott;
    private javax.swing.JButton jButtonCreateFruit;
    private javax.swing.JButton jButtonCreatePlat;
    private javax.swing.JButton jButtonRetrait;
    private javax.swing.JComboBox<String> jComboSelectAdd;
    private javax.swing.JComboBox<String> jComboSelectRetrait;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextInfos;
    // End of variables declaration//GEN-END:variables

    
    
    public void updateAffichage() {
        jComboSelectAdd.removeAllItems();
        if (!listeAdd.isEmpty()){
            for (ElementPanier p : listeAdd)
                jComboSelectAdd.addItem(p.toString());
        }
        jComboSelectRetrait.removeAllItems();
        if (!panier.getelements().isEmpty()){
            for (ElementPanier p : panier.getelements())
                jComboSelectRetrait.addItem(p.toString());
        }
        jTextInfos.setText(panier.toString());
    }
   
    @Override
    public void propertyChange(PropertyChangeEvent evt){
        Panier p = (Panier) evt.getSource();
        jTextInfos.setText(((Integer)p.getTaillePanier()).toString());
    }

    @Override
    public void addControleur(Controleur c) {
        this.jButtonAdd.addActionListener(c);
        this.jButtonRetrait.addActionListener(c);
        this.jComboSelectAdd.addActionListener(c);
        this.jComboSelectRetrait.addActionListener(c);
        this.jButtonBoycott.addActionListener(c);
        this.jButtonCreateFruit.addActionListener(c);
        this.jButtonCreatePlat.addActionListener(c);
        this.jButtonValiderBoycott.addActionListener(c);
        this.jButtonValiderCreateFruit.addActionListener(c);
        this.jButtonValiderCreatePlat.addActionListener(c);
        this.jComboSelectPlat.addActionListener(c);
        this.jComboSelectAddPlat.addActionListener(c);
        this.jComboSelectRetraitPlat.addActionListener(c);
        this.jBoutonRetirerFruitPlat.addActionListener(c);
        this.jBoutonAjouterFruitPlat.addActionListener(c);
        this.jButtonValiderAjoutPlat.addActionListener(c);
    }

    @Override
    public void ajout() {
        this.panier.ajout(this.listeAdd.get(numSelectAddFruit));
        updateAffichage();
    }

    @Override
    public void retrait() {
        this.panier.retrait(numSelectRetraitFruit);
        updateAffichage();
    }

    @Override
    public void selectRetrait() {
        this.numSelectRetraitFruit=this.jComboSelectRetrait.getSelectedIndex();
    }

    @Override
    public void selectAdd() {
        this.numSelectAddFruit=this.jComboSelectAdd.getSelectedIndex();
    }

    public void initFrameCreateFruit(){
        // Création de la fenêtre
        frame = new JFrame("Nouveau Fruit");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fermer uniquement la fenêtre actuelle
        frame.setSize(300, 150);

        // Création des composants
        JLabel labelNom = new JLabel("Nom:");
        final JTextField textFieldNom = new JTextField(20);

        JLabel labelNationalite = new JLabel("Nationalité:");
        final JTextField textFieldNationalite = new JTextField(20);

        JLabel labelPrix = new JLabel("Prix:");
        final JTextField textFieldPrix = new JTextField(20);

        
        listeParamCreateFruit.add(textFieldNom);
        listeParamCreateFruit.add(textFieldNationalite);
        listeParamCreateFruit.add(textFieldPrix);
        
        jButtonValiderCreateFruit.setName("ValiderCreateFruit");

        // Ajout des composants à la fenêtre
        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(4, 2));
        panel.add(labelNom);
        panel.add(textFieldNom);
        panel.add(labelNationalite);
        panel.add(textFieldNationalite);
        panel.add(labelPrix);
        panel.add(textFieldPrix);
        panel.add(jButtonValiderCreateFruit);

        frame.add(panel);

        frame.setVisible(true);
    }
    
    @Override
    public void createFruit() {
        this.listeParamCreateFruit.clear();
        this.initFrameCreateFruit();
        this.updateAffichage();
    }
    
    @Override
    public void validerCreateFruit() {
        String nom = listeParamCreateFruit.get(0).getText();
        String origine = listeParamCreateFruit.get(1).getText();
        String valeur = listeParamCreateFruit.get(2).getText();
              
        double prix = 1;
        
        try{
            prix = Double.parseDouble(valeur);
        } catch (NumberFormatException e) {
            
        }
               
        ElementPanier nouvelElement = fabrique.createFruit(nom,prix,origine);

        if (nouvelElement!=null) 
            listeAdd.add(nouvelElement);

        frame.dispose();
        this.updateAffichage();
    }

    public void initFrameBoycott(){
        frame = new JFrame("Boycott");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(300, 150);

        JLabel labelNom = new JLabel("Fruit:");
        final JTextField textFieldNom = new JTextField(20);

        JLabel labelNationalite = new JLabel("Nationalité:");
        final JTextField textFieldNationalite = new JTextField(20);
        
        JLabel labelPrix = new JLabel("Prix:");
        final JTextField textFieldPrix = new JTextField(20);

        listeParamBoycott.add(textFieldNom);
        listeParamBoycott.add(textFieldNationalite);
        listeParamBoycott.add(textFieldPrix);
        
        jButtonValiderBoycott.setName("ValiderBoycott");


        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(4, 2));
        panel.add(labelNom);
        panel.add(textFieldNom);
        panel.add(labelNationalite);
        panel.add(textFieldNationalite);
        panel.add(labelPrix);
        panel.add(textFieldPrix);
        panel.add(jButtonValiderBoycott);

        frame.add(panel);

        frame.setVisible(true);
    }
    
    @Override
    public void boycott() {
        this.listeParamBoycott.clear();
        this.initFrameBoycott();
        this.updateAffichage();
    }

    @Override
    public void validerBoycott() {
        String nom = listeParamBoycott.get(0).getText();
        String origine = listeParamBoycott.get(1).getText();
        String valeur = listeParamBoycott.get(2).getText();
        
        double prix = 100000000;
        
        try{
            prix = Double.parseDouble(valeur);
        } catch (NumberFormatException e) {
            
        }
        
        if (!nom.equals("")){
            if (!origine.equals("")){
                if (prix!=100000000){
                    this.panier.boycotteNamePrixOrigine(nom, prix, origine);
                } else {
                    this.panier.boycotteNameOrigine(nom, origine);
                }
            } else {
                if (prix!=100000000){
                    this.panier.boycotteNamePrix(nom, prix);
                } else {
                    this.panier.boycotteName(nom);
                }
            } 
        } else {
            if (!origine.equals("")){
                if (prix!=100000000){
                    this.panier.boycottePrixOrigine(prix, origine);
                } else {
                    this.panier.boycotteOrigine(origine);
                }
            } else {
                if (prix!=100000000){
                    this.panier.boycottePrix(prix);
                } else {
                    //Do nothing (aucun paramêtre)
                }
            } 
        }
        
        frame.dispose();
        this.updateAffichage();
    }

    public void initFrameCreatePlat(){
        frame = new JFrame("Nouveau Plat");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Fermer uniquement la fenêtre actuelle
        frame.setSize(500, 200);

        // Créer le label "Sélectionner un plat:"
        JLabel labelPlat = new JLabel("Sélectionner un plat:");
        // Créer une JComboBox pour les plats
        jComboSelectPlat.setName("SelectPlat");
        listePlatPossible.clear();
        jComboSelectPlat.removeAllItems();
        
        jComboSelectPlat.addItem("Jus");
        listePlatPossible.add("Jus");
        jComboSelectPlat.addItem("Salade");
        listePlatPossible.add("Salade");

        textAreaPlat = new JTextArea(5, 60);

        jComboSelectAddPlat.removeAllItems();
        jComboSelectAddPlat.setName("SelectAddPlat");
        for(ElementPanier p : listeAdd)
            if (p.getName()!="Jus"&&p.getName()!="Salade")
                jComboSelectAddPlat.addItem(p.toString());
        
        jComboSelectRetraitPlat.removeAllItems();
        jComboSelectRetraitPlat.setName("SelectRetraitPlat");
        
        jBoutonAjouterFruitPlat.setName("AjouterFruitPlat");
        jBoutonRetirerFruitPlat.setName("RetirerFruitPlat");
        jButtonValiderAjoutPlat.setName("ValiderCreatePlat");

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(5, 1));
        JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayout(1, 2)); 
        JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayout(1, 2)); 
        JPanel panel3 = new JPanel();
        JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayout(1, 2)); 
        JPanel panel5 = new JPanel();
        // Ajouter les composants au panneau
        panel1.add(labelPlat);
        panel1.add(jComboSelectPlat);
        panel2.add(jBoutonAjouterFruitPlat);
        panel2.add(jComboSelectAddPlat);
        panel3.add(textAreaPlat);
        panel4.add(jBoutonRetirerFruitPlat);
        panel4.add(jComboSelectRetraitPlat);
        panel5.add(jButtonValiderAjoutPlat);
        panel.add(panel1);
        panel.add(panel2);
        panel.add(panel3);
        panel.add(panel4);
        panel.add(panel5);
        frame.add(panel);

        frame.pack();
        frame.setVisible(true);
    }
    
    @Override
    public void createPlat(){
        if(!listeAdd.isEmpty()){
            this.listeParamCreatePlat.clear();
            this.initFrameCreatePlat();
            updateAffichagePlat();
        } else {
            this.createFruit();
        }
    }
    
    @Override
    public void validerCreatePlat() {
        if(!listePlatPossible.isEmpty()){
            if (!listeAddFruitPlat.isEmpty()){
                String nomPlat = listePlatPossible.get(numSelectPlat);
                ElementPanier newElem = this.fabrique.createPlat(nomPlat, listeAddFruitPlat);
                this.listeAdd.add(newElem);
            }
        }
        frame.dispose();
        updateAffichage();
    }

    @Override
    public void selectAddPlat() {
        this.numSelectAddFruitPlat=this.jComboSelectAddPlat.getSelectedIndex();
    }

    @Override
    public void selectRetraitPlat() {
        this.numSelectRetraitFruitPlat=this.jComboSelectRetraitPlat.getSelectedIndex();
    }

    @Override
    public void ajoutFruitPlat() {
        if(!listeAdd.isEmpty())
            this.listeAddFruitPlat.add(listeAdd.get(numSelectAddFruitPlat));
        this.updateAffichagePlat();
    }

    @Override
    public void retirerFruitPlat() {
        if(!listeAddFruitPlat.isEmpty())
            this.listeAddFruitPlat.remove(this.numSelectRetraitFruitPlat);
        this.updateAffichagePlat();
    }

    @Override
    public void selectPlat() {
        this.numSelectPlat=this.jComboSelectPlat.getSelectedIndex();
        this.updateAffichagePlat();
    }
    
    public void updateAffichagePlat(){
        String res = "";
        String newLine = System.getProperty("line.separator");
        if(!listePlatPossible.isEmpty())
            res += listePlatPossible.get(numSelectPlat)+newLine;
        if(!listeAddFruitPlat.isEmpty()) for (ElementPanier p : listeAddFruitPlat) 
            res += p.toString() + newLine;
        this.textAreaPlat.setText(res);
        for(ElementPanier p : listeAddFruitPlat)
            jComboSelectRetraitPlat.addItem(p.toString());
    }

}
